### ISSUE TITLE
Molly secondary device seems to lose connection after a while

### ISSUE THREAD

**Issue by AtiusAmy** [mollyim/mollyim-android#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I linked Molly as a secondary device and it works well however, after a while (and many messages sent from the primary device) it seems to stop getting new messages and the sync stop at a certain point. Oh and for some reason, if you chat on the secondary device the same bug will happen on the primary device (Which is just the default Signal). This might be related to the Signal linking changes in server but I am not sure.

Unlinking and Re-linking seems to fix the issue temporarily.

EDIT: It seens to not lose connection when I have long conversation on the Desktoo but loses connection when I do on my main phone

### Steps to reproduce

1. Link Device as a secondary device,
2. Have long conversation with someone on a primary device
3. Second device messages sync stop at a certain point

### Molly version

v6.41.3-2-FOSS

### Android version

Android 13

### Device

Xiaomi Mi Pad 5

### Link to debug log

https://debuglogs.org/android/6.41.3/f6771bccf303e14d9a46b9e4ae80a42f8a4f2e2c07532a1f3eae0b50b4fd4e0b

**Comment by AtiusAmy** [comment]
Also happens on Redmi Note 7 Android 11 too


Here is the debug log
https://debuglogs.org/android/6.41.3/9d21c8f3ec6315089f9866826e66feef080212cf6d9bf22a55e1d35ed5cbbfd9

**Comment by Uneccessary** [comment]
Happens also on Samsung devices, my friend and myself have also this issue.

**Comment by taivlam** [comment]
I experienced this issue 1 week ago.  The issue came back the very next day, but since 6 days ago this issue hasn't occurred again.

Below are debug logs: my main Molly device is the Pixel 5a (`barbet`) and my secondary Molly device is the Pixel Tablet (`tangorpro`).

### Before removing secondary device to fix issue
* Pixel 5a [debug log](https://debuglogs.org/android/6.41.3/1c261ccca0ec77ba8ecbb6a04e9dc0916be75f71e4ee65dc7319c050d250d701)
* Pixel Tablet [debug log](https://debuglogs.org/android/6.41.3/fb91610c3295b3941464e08d8190d36cd34fab71ff13f4e5aa088df5c33414ad)
### Before adding back signed out secondary device
* Pixel 5a [debug log](https://debuglogs.org/android/6.41.3/646bd40202a1e990bf0a8023e79ae1fbd2be57cc63dc4b8aadab491a7991fd7f)
* Pixel Tablet [debug log](https://debuglogs.org/android/6.41.3/6ce104650c6920f2d20b45f0c6418f8c300344d6c4622ac2b47defcc8f43b425)

**Comment by AtiusAmy** [comment]
> I experienced this issue 1 week ago.  The issue came back the very next day, but since 6 days ago this issue hasn't occurred again.
> 
> Below are debug logs: my main Molly device is the Pixel 5a (`barbet`) and my secondary Molly device is the Pixel Tablet (`tangorpro`).
> 
> ### Before removing secondary device to fix issue
> * Pixel 5a [debug log](https://debuglogs.org/android/6.41.3/1c261ccca0ec77ba8ecbb6a04e9dc0916be75f71e4ee65dc7319c050d250d701)
> * Pixel Tablet [debug log](https://debuglogs.org/android/6.41.3/fb91610c3295b3941464e08d8190d36cd34fab71ff13f4e5aa088df5c33414ad)
> ### Before adding back signed out secondary device
> * Pixel 5a [debug log](https://debuglogs.org/android/6.41.3/646bd40202a1e990bf0a8023e79ae1fbd2be57cc63dc4b8aadab491a7991fd7f)
> * Pixel Tablet [debug log](https://debuglogs.org/android/6.41.3/6ce104650c6920f2d20b45f0c6418f8c300344d6c4622ac2b47defcc8f43b425)
> 
> 
 Same! The last 6 days has been pretty amooth for me too

**Comment by valldrac** [comment]
Can you try updating to the version [6.44.2-1](https://github.com/mollyim/mollyim-android/releases/tag/v6.44.2-1), please? This bug should be fixed now.

**Comment by Uneccessary** [comment]
Yes, I will, I will report back when the issue appears still again

**Comment by AtiusAmy** [comment]
> Can you try updating to the version [6.44.2-1](https://github.com/mollyim/mollyim-android/releases/tag/v6.44.2-1), please? This bug should be fixed now.

I still have the issue

https://debuglogs.org/android/6.44.3/c499bf837734ac858b3eeadd5460c890d3bf7c15394f6921f6fbcab36a4f7f44

**Comment by taivlam** [comment]
This started again about 3 days ago, though it also happened today.

I observed this issue occurs on my main Molly device within 10 minutes after my secondary Molly device is online (which also affects my Signal Desktop devices).

### Pinned messages get messed up
* Pixel 5a (main Molly device) [logs](https://debuglogs.org/android/6.44.3/05542ed1f5eefb1f866a896f3d9eea79f9e83b529cbb5ebedcd9ea4ea3a3a193)
* Pixel Tablet (secondary Molly device) [logs](https://debuglogs.org/android/6.44.3/72fcba01e201d1909fce4536a2052ff2d89e150a3e082f15b7257eda0946c268)
### After fixing pinned messages on main device only
* Pixel 5a (main Molly device) [logs](https://debuglogs.org/android/6.44.3/b91ec7a213bbf1a956782ee5d160871c0ae2e443f4a966c2d3fe6140433bff7a)
* Pixel Tablet (secondary Molly device) [logs](https://debuglogs.org/android/6.44.3/6881d2761a1a5ea8ab643abaff3fb6f2661c3847f424f86512a41b4e5e06c5c5)

**Comment by valldrac** [comment]
I'm working on a new beta release v6.45.2-1 with the fix. It should be ready to download in about an hour. Can you please try it and let me know how it goes?

**Comment by taivlam** [comment]
1)  (I'm aware the fix is being work on right now, though @valldrac beat me before I could comment.)

This issue occured started 5 days ago again.  I had to relink my secondary Molly device yesterday.

### Before relinking
* Pixel 5a (main Molly device) [log](https://debuglogs.org/android/6.44.3/f2af126193df5333167e1c6d888b55d7c4385c59116e372599264a89f1533f03)
* Pixel Tablet (secondary Molly device) [log](https://debuglogs.org/android/6.44.3/9816c77c580c639a3e9cfe47c070733b30d122728c7ff5555d962e38efecb3f8)
### After relinking
* Pixel 5a (main Molly device) [log](https://debuglogs.org/android/6.44.3/61fda4b1fd13ca916510f21255612a095ec02586815d6f1a04a17c15ff553e54)
* Pixel Tablet (secondary Molly device) [log](https://debuglogs.org/android/6.44.3/f690a4ce2059e3c2eefc11c940605d8dac04722d48dc2792b66b5063a28da509)

2)  I would be willing to test beta release `v6.45.2-1`.  For this purpose, will [Molly Insider](https://github.com/mollyim/mollyim-insider-android) work in parallel on the same Android user profile as my main Molly client?

**Comment by valldrac** [comment]
@taivlam We don't roll out beta versions in Molly Insider anymore. Betas are just another version of Molly now, but released gradually. To switch to a beta version, enable the option in Settings > Help, or do it through your f-droid client, or download the APK directly from GitHub Releases.

**Comment by taivlam** [comment]
@valldrac Will this work if you've downloaded Molly through Accrescent?

**Comment by valldrac** [comment]
> Will this work if you've downloaded Molly through Accrescent?

Yes, you can install the beta from GitHub, but just keep in mind that Accrescent will stop updating the app automatically. If you want to resume updates later, you'll have to install it manually at least once through the Accrescent app.

> (I don't see any options relating to the beta version.)

Because Accrescent doesn't support beta versions yet.

**Comment by taivlam** [comment]
3 days ago I downloaded `v6.45.2-1`.  (I simply enabled the Molly repo in Droid-ify and updated the beta version over the version I downloaded through Accrescent; though I'll update Molly via Accrescent for future Molly production updates.)

The link to my secondary Molly device seems to be alright for now.  I'll make another comment here if the issue ever occurs again (but hopefully not).
